### ISSUE TITLE
Drop Windows support fully

### ISSUE THREAD

**Issue by deavmi** [cdpxe/WendzelNNTPd#10]
I added to the todo list text file with some small improvements that could be made.

I saw that there was references to Win32 in the source code. Seeing that Windows is no longer supported (God forbid such a terrible platform for programming) should those references be removed then?

**Comment by cdpxe** [comment]
Okay. Just please be careful. Like in the OpenBSD project, we should double-check each other's commits from now on.

**Comment by deavmi** [comment]
Ah. I wasn't planning on doing any code changes (as I am still busy learning C when I can (in first year but I like reading ahead in my own time)).

Was just pointing it out. However, when I do become better I shall follow those guidelines. OpenBSD is secure for those purposes.

**Comment by cdpxe** [comment]
Oh, alright, then I better do the coding as mistakes are quite easy to make and I know the code quite well :)

**Comment by deavmi** [comment]
Yeah, especially since this is C (lots can go wrong very fast from my slight experience I have had with it) - although that is what I love about it (not the going wrong I guess but the flexibility).

**Comment by cdpxe** [comment]
thx.

**Comment by cdpxe** [comment]
Closing issue b/c the Win32 code does not really hurt but removing it might lead to new bugs if done not careful enough. For this reason, I will close this issue.
