### ISSUE TITLE
Move all database files to a `database/` directoory

### ISSUE THREAD

**Issue by deavmi** [cdpxe/WendzelNNTPd#11]
I am busy moving files like the `.sql` ones from the root of the repo to `/database`. I have not commit these changes yet as I am making sure all references to these files (but only the correct ones) are updated to point to `database/[file]`.

**Comment by deavmi** [comment]
I will do a thorough re-check before this commit and will test compilation too.

**Comment by cdpxe** [comment]
This should help a little to find references:

`$~/git/WendzelNNTPd$ grep -r *.sql *`

`create_code_pkg.sh:cp -v AUTHOR BUGS build CHANGELOG configure CONTRIBUTE FAQ.txt HISTORY INSTALL LICENSE log.txt Makefile README tiny_doc.txt usenet.db wendzelnntpd.conf re_create_db.sh TODO usenet.db_struct usenet.db_struct_clear mysql_db_struct.sql getver.sh $DST/`

`docs/docs/docs.html:For MySQL, a SQL script file is included called <I>mysql_db_struct.sql</I>. It creates the WendzelNNTPd database as well as all needed tables. Use the MySQL console tool to execute the script.`

`docs/docs/index.html:For MySQL, a SQL script file is included called <I>mysql_db_struct.sql</I>. It creates the WendzelNNTPd database as well as all needed tables. Use the MySQL console tool to execute the script.`

`Makefile:DOCFILES_TO_INST=AUTHOR CHANGELOG HISTORY README INSTALL LICENSE usenet.db_struct mysql_db_struct.sql`

**Comment by deavmi** [comment]
I will double-check those now.

**Comment by deavmi** [comment]
There was a section about the MySQL one that was a bit tricky but I think I got it. Commited now.

**Comment by deavmi** [comment]
Line 118 of the `Makefile` not sure if that should be `database/usenet.db` I assume it should be (and updated it to be so). It is a comment but just want to make sure it is clear.

**Comment by cdpxe** [comment]
The filenames (new markdown filename endings) etc. also had to be adjusted in create_code_pkg.sh and in the Makefile. I adjusted things now.

I propose (due to the fact that we might face additional side-effects) to not switch directories for files anymore until very necessary. Let's instead polish what is there.

I think, we can release a new version when done with all this. At least, when the hashing code is finalized (I will work on it in the coming week).

**Comment by deavmi** [comment]
Good to hear. I will keep that in mind.

**Comment by deavmi** [comment]
I will close this after I compile and test at home (this weekend).
