### ISSUE TITLE
[Future] Move Database Backends to a "backends/" directory

### ISSUE THREAD

**Issue by deavmi** [cdpxe/WendzelNNTPd#14]
Just putting this here for the future to further modularise it all.

I assume only the abstraction library will need updating to the new pathnames for the current databases we support.

**Comment by cdpxe** [comment]
Hi, sorry, but its too few files; I would keep that all in src/. Changing directories can negatively influence stability/inner-workings of the package.

**Comment by deavmi** [comment]
Alright. Will close.
