### ISSUE TITLE
Maximum filesize for attachments

### ISSUE THREAD

**Issue by pintman** [cdpxe/WendzelNNTPd#2]
Is there any maximum size for attachments? 10 MB seem to work very well. 20 MB will accepted but are not shown. No error in the logs.

**Comment by cdpxe** [comment]
Yes. see ./src/include/wendzelnntpdpath.h
Change the value of MAX_POSTSIZE which by default should accept 20*1024*1024 bytes.

**Comment by cdpxe** [comment]
2nd update: I added new code to the repository.
Please download the new version that now allows to set the value max. allowed posting size in the configuration file via

max-size-of-postings 20971520

(the value must be in bytes).

Please let me know whether this works on your system.

Thanks, St.

**Comment by pintman** [comment]
I tried it on a local machine with up to 50 MB in a MySQL-DB which seems to work. :)

Thanks for the new option and the fast support.
