### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by deavmi** [cdpxe/WendzelNNTPd#4]
I noticed some broken English in the PDF documentation and I really love this piece of software, could I submit a PR?

**Comment by cdpxe** [comment]
Dear deavmi, sure, any help is welcome.

**Comment by deavmi** [comment]
I didn't want to come accross as rude. Just thought I could help (your documentation is great anyways).

On 22 April 2018 08:04:52 SAST, Steffen Wendzel <notifications@github.com> wrote:
>Dear deavmi, sure, any help is welcome.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cdpxe/WendzelNNTPd/issues/4#issuecomment-383358013

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deavmi** [comment]
I will finalize my changes at the end of this week (SAST).

**Comment by cdpxe** [comment]
Great, many thanks!

**Comment by deavmi** [comment]
It's an absolute pleasure. I really love seeing good projects out there and written in C too (more beautiful). Also I was looking for an easy to set-up NNTP server (INN was too confusing).

Also the fact you use TeX for the documentation makes it even better (knowing you're an academic makes it obvious that you'd use it - which is great! :+1:).

I have tested it on my home network and it works great!

**Comment by deavmi** [comment]
PR is here now #6

**Comment by deavmi** [comment]
Yeah I think it just grew too complex to be honest, in general I found it hard to setup as in I never got anything to work - it is a bit archaic in that sense.

TLS support would of course be nice but for now it is fine (I never send sensitive data over NNTP, I use public access servers on usenet that require no authentication). But in this day and age, security is key.

**Comment by deavmi** [comment]
Whenever you have time you can rebuild the documentation, maybe once I have neared completion of my changes.

Don't want to do it for each PR ;).

**Comment by cdpxe** [comment]
Excellent! I accepted all changes and updated the PDF/HTML docs accordingly. Let me know if you have more fixes.

**Comment by deavmi** [comment]
Will do!

**Comment by deavmi** [comment]
I just noticed that both are profile pictures are pretty classy too. Just saying :)

**Comment by deavmi** [comment]
Is there anything that the documentation is possibly lacking. As I think I have worked out atleast most of it. Just want to know if there is anything at all I could add to it. Any rough ideas?

**Comment by cdpxe** [comment]
Hm, I don't know, to be honest. However, from the developer perspective, it's bit difficult to tell sometimes. When you set up the server, did you had any trouble? Important questions that arose and that are not included in the docs?

**Comment by deavmi** [comment]
It is difficult to tell from such a perspective. Maybe I will come up with something.
