### ISSUE TITLE
Move old version source code to a new branch

### ISSUE THREAD

**Issue by deavmi** [cdpxe/WendzelNNTPd#5]
I was thinking that it would be mice to rather expand the current version into the root of the repositoty and then move the old version (and do the same) in a new branch.

**Comment by cdpxe** [comment]
yes, sounds fine to me. I will do this in the coming days.

**Comment by deavmi** [comment]
Awesome

On 22 April 2018 08:05:49 SAST, Steffen Wendzel <notifications@github.com> wrote:
>yes, sounds fine to me. I will do this in the coming days.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cdpxe/WendzelNNTPd/issues/5#issuecomment-383358059

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cdpxe** [comment]
Change was made right now. I will lose this issue now.

**Comment by deavmi** [comment]
Awesome.

On 22 April 2018 16:29:13 SAST, Steffen Wendzel <notifications@github.com> wrote:
>Change was made right now. I will lose this issue now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cdpxe/WendzelNNTPd/issues/5#issuecomment-383385530

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
