### ISSUE TITLE
Other ideas for the project [non-code]

### ISSUE THREAD

**Issue by deavmi** [cdpxe/WendzelNNTPd#8]
I was just wondering if a simple GitHub pages website would be useful for the project. Maybe with a short description of the and links to the repository and builds (I don't know if therr are any services that offer some sort of CI that also hosts builds).

**Comment by deavmi** [comment]
I'd setup a build server for this project anyday (when I find time).

**Comment by cdpxe** [comment]
Hi, good idea. I'm a bit busy this week. However, would you be interested in joining the project officially? I would then give you the right to perform own contributions, especially related to the documentation and a website. -Steffen

**Comment by cdpxe** [comment]
PS. I created a branch gh-pages that is used to automatically generate the website.

**Comment by deavmi** [comment]
It would probably make life a lot easier if I had commit access so that I could do such things, yes that would be very much appreciated. :)

**Comment by deavmi** [comment]
I have tested it and made several commits and it is working.

Thanks :).
